import type {
  Recipe,
  RecipeCategory,
  RecipeProfile,
  WeekDay,
  WeekPlan,
} from './model';

const imageParams = '?auto=format&fit=crop&w=1000&q=82';

export const recipeColors = {
  background: '#FAFCFB',
  surface: '#FFFFFF',
  surfaceMuted: '#F1F6F3',
  ink: '#17352B',
  muted: '#61716B',
  faint: '#8B9893',
  line: '#E1E8E4',
  orange: '#D56C28',
  orangeSoft: '#FFF1E8',
  sage: '#DCEDE2',
  warningSoft: '#FFF6E5',
  warning: '#A26112',
} as const;

export const weekDays: WeekDay[] = [
  { id: 'mon', weekday: '一', label: '周一', date: '17', fullDate: '8月17日', isToday: true },
  { id: 'tue', weekday: '二', label: '周二', date: '18', fullDate: '8月18日' },
  { id: 'wed', weekday: '三', label: '周三', date: '19', fullDate: '8月19日' },
  { id: 'thu', weekday: '四', label: '周四', date: '20', fullDate: '8月20日' },
  { id: 'fri', weekday: '五', label: '周五', date: '21', fullDate: '8月21日' },
  { id: 'sat', weekday: '六', label: '周六', date: '22', fullDate: '8月22日' },
  { id: 'sun', weekday: '日', label: '周日', date: '23', fullDate: '8月23日' },
];

export const recipes: Recipe[] = [
  {
    id: 'oat-egg',
    title: '燕麦坚果碗配水煮蛋',
    image: `https://images.unsplash.com/photo-1517673400267-0251440c45dc${imageParams}`,
    imageDescription: '燕麦、蓝莓、香蕉和坚果早餐碗',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 12,
    difficulty: '容易',
    servings: 1,
    calories: 410,
    protein: 21,
    carbs: 48,
    fiber: 9,
    recommendation: '全谷物早餐，上午更耐饿',
    description: '用燕麦、酸奶和鸡蛋组成的快手早餐，口感清爽，适合工作日。',
    mealSlots: ['breakfast'],
    categories: ['recommended', 'quick', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    tags: ['全谷物', '少添加糖', '12分钟'],
    allergens: ['乳制品', '坚果', '蛋类'],
    ingredients: [
      { id: 'oats', name: '燕麦片', amount: '50 克', group: 'staple' },
      { id: 'yogurt', name: '无糖酸奶', amount: '150 克', group: 'protein' },
      { id: 'egg', name: '鸡蛋', amount: '1 个', group: 'protein' },
      { id: 'blueberry', name: '蓝莓', amount: '40 克', group: 'produce' },
      { id: 'walnut', name: '核桃仁', amount: '10 克', group: 'seasoning' },
    ],
    steps: [
      { title: '煮鸡蛋', description: '鸡蛋冷水下锅，水开后煮 7 分钟。', timerMinutes: 7, ingredients: ['鸡蛋'] },
      { title: '冲泡燕麦', description: '燕麦加入热水焖 3 分钟，稍微放凉。', timerMinutes: 3, ingredients: ['燕麦片'] },
      { title: '组合早餐碗', description: '加入无糖酸奶、蓝莓和核桃仁，鸡蛋对半切开后搭配食用。', ingredients: ['无糖酸奶', '蓝莓', '核桃仁'] },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'wholegrain-sandwich',
    title: '全麦鸡蛋蔬菜三明治',
    image: `https://images.unsplash.com/photo-1528735602780-2552fd46c7af${imageParams}`,
    imageDescription: '全麦面包夹鸡蛋和新鲜蔬菜',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 15,
    difficulty: '容易',
    servings: 1,
    calories: 385,
    protein: 24,
    carbs: 42,
    fiber: 7,
    recommendation: '15 分钟完成，适合忙碌早晨',
    description: '全麦面包搭配鸡蛋和清爽蔬菜，便于携带，也可以提前一晚准备食材。',
    mealSlots: ['breakfast'],
    categories: ['quick', 'fat-loss'],
    goals: ['balanced', 'fat-loss', 'muscle-gain'],
    tags: ['快手早餐', '高蛋白', '可携带'],
    allergens: ['麸质', '蛋类'],
    ingredients: [
      { id: 'bread', name: '全麦面包', amount: '2 片', group: 'staple' },
      { id: 'egg', name: '鸡蛋', amount: '1 个', group: 'protein' },
      { id: 'lettuce', name: '生菜', amount: '2 片', group: 'produce' },
      { id: 'tomato', name: '番茄', amount: '半个', group: 'produce' },
      { id: 'pepper', name: '黑胡椒', amount: '少许', group: 'seasoning' },
    ],
    steps: [
      { title: '煎鸡蛋', description: '平底锅少油，将鸡蛋煎至蛋白凝固。', timerMinutes: 4, ingredients: ['鸡蛋'] },
      { title: '处理蔬菜', description: '生菜洗净沥干，番茄切薄片。', ingredients: ['生菜', '番茄'] },
      { title: '组合三明治', description: '依次放入生菜、番茄和鸡蛋，撒黑胡椒后合上面包。' },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'millet-pumpkin',
    title: '南瓜小米粥配豆腐干',
    image: `https://images.unsplash.com/photo-1547592166-23ac45744acd${imageParams}`,
    imageDescription: '南瓜小米粥与清淡配菜',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 30,
    difficulty: '容易',
    servings: 2,
    calories: 360,
    protein: 18,
    carbs: 55,
    fiber: 8,
    recommendation: '清淡温和，搭配豆制品更均衡',
    description: '南瓜自然甜味搭配小米，加入豆腐干补充蛋白质，适合早餐或清淡晚餐。',
    mealSlots: ['breakfast', 'dinner'],
    categories: ['seasonal', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'steady-sugar'],
    tags: ['清淡', '粗杂粮', '秋季'],
    allergens: ['大豆'],
    ingredients: [
      { id: 'millet', name: '小米', amount: '80 克', group: 'staple' },
      { id: 'pumpkin', name: '南瓜', amount: '200 克', group: 'produce' },
      { id: 'tofu-dry', name: '豆腐干', amount: '100 克', group: 'protein' },
      { id: 'bok-choy', name: '小青菜', amount: '120 克', group: 'produce' },
    ],
    steps: [
      { title: '准备食材', description: '南瓜去皮切小块，小米淘洗一次。', ingredients: ['南瓜', '小米'] },
      { title: '熬煮', description: '小米和南瓜加入约 800 毫升水，小火煮至软糯。', timerMinutes: 25 },
      { title: '准备配菜', description: '豆腐干切片，小青菜焯水后一起装盘。', timerMinutes: 3 },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'tomato-beef',
    title: '番茄牛腩配杂粮饭',
    image: `https://images.unsplash.com/photo-1547592180-85f173990554${imageParams}`,
    imageDescription: '番茄炖牛肉搭配杂粮饭',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 45,
    difficulty: '适中',
    servings: 2,
    calories: 625,
    protein: 42,
    carbs: 68,
    fiber: 10,
    recommendation: '高蛋白，番茄风味适合家常午餐',
    description: '番茄的酸甜与牛腩慢炖后的浓郁搭配杂粮饭，适合一次做两份。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['recommended', 'seasonal', 'muscle-gain'],
    goals: ['balanced', 'muscle-gain'],
    tags: ['高蛋白', '一锅炖', '可备餐'],
    allergens: [],
    ingredients: [
      { id: 'beef', name: '牛腩', amount: '350 克', group: 'protein' },
      { id: 'tomato', name: '番茄', amount: '3 个', group: 'produce' },
      { id: 'onion', name: '洋葱', amount: '半个', group: 'produce' },
      { id: 'mixed-rice', name: '杂粮米', amount: '120 克', group: 'staple' },
      { id: 'soy-sauce', name: '低盐生抽', amount: '1 汤匙', group: 'seasoning' },
    ],
    steps: [
      { title: '处理牛腩', description: '牛腩切块后冷水下锅，煮开撇去浮沫并沥干。', timerMinutes: 8, ingredients: ['牛腩'] },
      { title: '炒出番茄汁', description: '洋葱炒香，加入番茄块翻炒至出汁。', timerMinutes: 6, ingredients: ['番茄', '洋葱'] },
      { title: '小火炖煮', description: '加入牛腩和热水没过食材，小火炖至牛腩软烂。', timerMinutes: 30 },
      { title: '调味装盘', description: '加入低盐生抽，搭配提前煮好的杂粮饭。', ingredients: ['低盐生抽', '杂粮米'] },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'chicken-brown-rice',
    title: '香煎鸡胸糙米蔬菜碗',
    image: `https://images.unsplash.com/photo-1603133872878-684f208fb84b${imageParams}`,
    imageDescription: '鸡胸肉、糙米和西兰花组成的蔬菜碗',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 30,
    difficulty: '容易',
    servings: 1,
    calories: 560,
    protein: 46,
    carbs: 58,
    fiber: 11,
    recommendation: '蛋白质充足，搭配全谷物和两种蔬菜',
    description: '适合工作日备餐的均衡碗，调味克制，食材可以灵活替换。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['recommended', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    tags: ['高蛋白', '全谷物', '可备餐'],
    allergens: [],
    ingredients: [
      { id: 'chicken', name: '鸡胸肉', amount: '180 克', group: 'protein' },
      { id: 'brown-rice', name: '糙米', amount: '70 克', group: 'staple' },
      { id: 'broccoli', name: '西兰花', amount: '160 克', group: 'produce' },
      { id: 'carrot', name: '胡萝卜', amount: '半根', group: 'produce' },
      { id: 'olive-oil', name: '橄榄油', amount: '1 茶匙', group: 'seasoning' },
    ],
    steps: [
      { title: '煮糙米', description: '糙米提前浸泡后按正常米饭方式煮熟。', timerMinutes: 25, ingredients: ['糙米'] },
      { title: '处理鸡胸肉', description: '鸡胸肉拍松，加少量盐和黑胡椒腌 5 分钟。', timerMinutes: 5, ingredients: ['鸡胸肉'] },
      { title: '煎鸡胸肉', description: '平底锅刷橄榄油，中小火将鸡胸肉两面煎熟。', timerMinutes: 10 },
      { title: '组合蔬菜碗', description: '西兰花和胡萝卜焯熟，与糙米、切片鸡胸肉一起装碗。' },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'salmon-vegetables',
    title: '香煎三文鱼配时蔬',
    image: `https://images.unsplash.com/photo-1467003909585-2f8a72700288${imageParams}`,
    imageDescription: '煎三文鱼搭配绿色时蔬',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 25,
    difficulty: '容易',
    servings: 1,
    calories: 510,
    protein: 38,
    carbs: 32,
    fiber: 9,
    recommendation: '鱼类蛋白和丰富蔬菜，晚餐负担较轻',
    description: '三文鱼用平底锅快速煎熟，搭配当季绿色蔬菜和少量薯类。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['seasonal', 'fat-loss', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    tags: ['优质脂肪', '低添加糖', '25分钟'],
    allergens: ['鱼类'],
    ingredients: [
      { id: 'salmon', name: '三文鱼', amount: '160 克', group: 'protein' },
      { id: 'asparagus', name: '芦笋', amount: '120 克', group: 'produce' },
      { id: 'potato', name: '小土豆', amount: '120 克', group: 'staple' },
      { id: 'lemon', name: '柠檬', amount: '四分之一个', group: 'produce' },
      { id: 'pepper', name: '黑胡椒', amount: '少许', group: 'seasoning' },
    ],
    steps: [
      { title: '准备配菜', description: '小土豆切块蒸熟，芦笋去老根。', timerMinutes: 12, ingredients: ['小土豆', '芦笋'] },
      { title: '煎三文鱼', description: '三文鱼擦干，两面撒黑胡椒，中火煎至中心刚熟。', timerMinutes: 8, ingredients: ['三文鱼'] },
      { title: '煎香蔬菜', description: '原锅加入芦笋和土豆，快速翻炒上色。', timerMinutes: 4 },
      { title: '装盘', description: '挤少量柠檬汁后装盘，不额外添加甜味酱汁。', ingredients: ['柠檬'] },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'tofu-shrimp',
    title: '虾仁豆腐时蔬煲',
    image: `https://images.unsplash.com/photo-1512058564366-18510be2db19${imageParams}`,
    imageDescription: '虾仁、豆腐与绿色蔬菜组成的热菜',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 28,
    difficulty: '容易',
    servings: 2,
    calories: 470,
    protein: 37,
    carbs: 39,
    fiber: 8,
    recommendation: '豆制品与虾仁组合，口味清淡但有满足感',
    description: '一锅完成的家常热菜，适合搭配少量杂粮饭。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['quick', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    tags: ['一锅完成', '高蛋白', '清淡'],
    allergens: ['甲壳类', '大豆'],
    ingredients: [
      { id: 'shrimp', name: '虾仁', amount: '180 克', group: 'protein' },
      { id: 'tofu', name: '北豆腐', amount: '250 克', group: 'protein' },
      { id: 'mushroom', name: '鲜香菇', amount: '100 克', group: 'produce' },
      { id: 'bok-choy', name: '小青菜', amount: '180 克', group: 'produce' },
      { id: 'soy-sauce', name: '低盐生抽', amount: '2 茶匙', group: 'seasoning' },
    ],
    steps: [
      { title: '处理食材', description: '豆腐切块，香菇切片，小青菜洗净。', ingredients: ['北豆腐', '鲜香菇', '小青菜'] },
      { title: '煎豆腐', description: '平底锅少油，将豆腐两面煎至微黄。', timerMinutes: 6, ingredients: ['北豆腐'] },
      { title: '焖煮', description: '加入香菇、虾仁和少量热水，盖盖焖至虾仁变色。', timerMinutes: 7 },
      { title: '加入青菜', description: '放入小青菜和低盐生抽，翻匀后即可。', timerMinutes: 2 },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'mushroom-chicken-rice',
    title: '菌菇鸡肉焖饭',
    image: `https://images.unsplash.com/photo-1512621776951-a57141f2eefd${imageParams}`,
    imageDescription: '菌菇鸡肉与蔬菜组成的一锅焖饭',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 40,
    difficulty: '适中',
    servings: 2,
    calories: 590,
    protein: 35,
    carbs: 72,
    fiber: 9,
    recommendation: '一锅完成，适合提前准备两餐',
    description: '鸡腿肉、菌菇和杂粮米一起焖熟，减少洗锅，也方便第二天带饭。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['seasonal', 'muscle-gain'],
    goals: ['balanced', 'muscle-gain'],
    tags: ['一锅完成', '可备餐', '菌菇'],
    allergens: ['大豆'],
    ingredients: [
      { id: 'chicken-leg', name: '去皮鸡腿肉', amount: '260 克', group: 'protein' },
      { id: 'mixed-rice', name: '杂粮米', amount: '150 克', group: 'staple' },
      { id: 'mushroom', name: '混合菌菇', amount: '180 克', group: 'produce' },
      { id: 'carrot', name: '胡萝卜', amount: '半根', group: 'produce' },
      { id: 'soy-sauce', name: '低盐生抽', amount: '1 汤匙', group: 'seasoning' },
    ],
    steps: [
      { title: '腌鸡肉', description: '鸡腿肉切块，加一半生抽腌 10 分钟。', timerMinutes: 10 },
      { title: '处理配菜', description: '菌菇切片，胡萝卜切丁，杂粮米淘洗。' },
      { title: '组合入锅', description: '杂粮米铺底，依次放入鸡肉、菌菇和胡萝卜，加适量水。' },
      { title: '焖熟', description: '按下煮饭键，完成后焖 5 分钟并翻匀。', timerMinutes: 5 },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'beef-noodle',
    title: '番茄荞麦牛肉面',
    image: `https://images.unsplash.com/photo-1563379926898-05f4575a45d8${imageParams}`,
    imageDescription: '番茄汤底荞麦面搭配牛肉和青菜',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 25,
    difficulty: '容易',
    servings: 1,
    calories: 545,
    protein: 34,
    carbs: 66,
    fiber: 9,
    recommendation: '用荞麦面替换精制面条，蔬菜量更充足',
    description: '酸甜番茄汤底搭配荞麦面和瘦牛肉，适合想吃面食的工作日晚餐。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['quick', 'steady-sugar'],
    goals: ['balanced', 'muscle-gain', 'steady-sugar'],
    tags: ['荞麦', '一人食', '25分钟'],
    allergens: ['麸质'],
    ingredients: [
      { id: 'buckwheat-noodle', name: '荞麦面', amount: '90 克', group: 'staple' },
      { id: 'beef-slice', name: '瘦牛肉片', amount: '120 克', group: 'protein' },
      { id: 'tomato', name: '番茄', amount: '2 个', group: 'produce' },
      { id: 'bok-choy', name: '小青菜', amount: '120 克', group: 'produce' },
      { id: 'soy-sauce', name: '低盐生抽', amount: '1 茶匙', group: 'seasoning' },
    ],
    steps: [
      { title: '煮番茄汤', description: '番茄切块炒软，加热水煮出味道。', timerMinutes: 8 },
      { title: '煮面', description: '另起锅煮荞麦面，捞出后放入番茄汤。', timerMinutes: 6 },
      { title: '加入牛肉和青菜', description: '牛肉片和青菜放入汤中，煮至牛肉刚熟。', timerMinutes: 3 },
      { title: '调味', description: '加入低盐生抽，尝味后再决定是否补盐。' },
    ],
    sourceLabel: '本地演示菜谱',
  },
  {
    id: 'shrimp-vegetables',
    title: '彩椒虾仁炒时蔬',
    image: `https://images.unsplash.com/photo-1540189549336-e6e99c3679fe${imageParams}`,
    imageDescription: '彩椒、荷兰豆和虾仁组成的清爽热菜',
    imageCredit: 'Unsplash 演示图片',
    timeMinutes: 18,
    difficulty: '容易',
    servings: 2,
    calories: 430,
    protein: 36,
    carbs: 35,
    fiber: 10,
    recommendation: '18 分钟快手菜，一餐吃到多种颜色蔬菜',
    description: '利用大火快炒保留蔬菜口感，搭配虾仁和少量杂粮饭即可成餐。',
    mealSlots: ['lunch', 'dinner'],
    categories: ['quick', 'fat-loss', 'steady-sugar'],
    goals: ['balanced', 'fat-loss', 'muscle-gain', 'steady-sugar'],
    tags: ['18分钟', '多彩蔬菜', '高蛋白'],
    allergens: ['甲壳类'],
    ingredients: [
      { id: 'shrimp', name: '虾仁', amount: '200 克', group: 'protein' },
      { id: 'pepper-color', name: '彩椒', amount: '1 个', group: 'produce' },
      { id: 'snow-pea', name: '荷兰豆', amount: '120 克', group: 'produce' },
      { id: 'mushroom', name: '口蘑', amount: '100 克', group: 'produce' },
      { id: 'olive-oil', name: '橄榄油', amount: '1 茶匙', group: 'seasoning' },
    ],
    steps: [
      { title: '处理食材', description: '彩椒切块，荷兰豆去筋，口蘑切片。' },
      { title: '炒虾仁', description: '锅烧热后加橄榄油，虾仁炒至变色后盛出。', timerMinutes: 3 },
      { title: '快炒蔬菜', description: '原锅放入全部蔬菜，大火翻炒至断生。', timerMinutes: 4 },
      { title: '混合出锅', description: '虾仁回锅，加入少量盐和黑胡椒翻匀。', timerMinutes: 1 },
    ],
    sourceLabel: '本地演示菜谱',
  },
];

export const categoryOptions: { id: RecipeCategory; label: string }[] = [
  { id: 'recommended', label: '为你推荐' },
  { id: 'quick', label: '快手菜' },
  { id: 'seasonal', label: '时令' },
  { id: 'fat-loss', label: '减脂' },
  { id: 'muscle-gain', label: '增肌' },
  { id: 'steady-sugar', label: '健康控糖' },
];

export const initialWeekPlan: WeekPlan = {
  mon: { breakfast: 'oat-egg', lunch: 'chicken-brown-rice', dinner: 'salmon-vegetables' },
  tue: { breakfast: 'wholegrain-sandwich', lunch: 'tomato-beef', dinner: 'tofu-shrimp' },
  wed: { breakfast: 'millet-pumpkin', lunch: 'mushroom-chicken-rice', dinner: 'shrimp-vegetables' },
  thu: { breakfast: 'oat-egg', lunch: 'beef-noodle', dinner: 'salmon-vegetables' },
  fri: { breakfast: 'wholegrain-sandwich', lunch: 'chicken-brown-rice', dinner: 'tofu-shrimp' },
  sat: { breakfast: 'millet-pumpkin', lunch: 'tomato-beef', dinner: 'shrimp-vegetables' },
  sun: { breakfast: 'oat-egg', lunch: 'mushroom-chicken-rice', dinner: 'beef-noodle' },
};

export const defaultProfile: RecipeProfile = {
  goal: 'steady-sugar',
  age: '31',
  sex: 'female',
  height: '165',
  weight: '60',
  targetWeight: '58',
  activity: 'moderate',
  allergies: [],
  dietaryRestrictions: [],
  diagnosedDiabetes: false,
  people: 1,
  maxCookingMinutes: 40,
  budget: 'standard',
  tastes: ['清淡', '家常'],
  equipment: ['炒锅', '电饭煲'],
};

export function getRecipe(recipeId: string) {
  return recipes.find((recipe) => recipe.id === recipeId);
}
